dvsa/olcs-backend

module/Api/src/Service/Document/Bookmark/Snippet/GB_STANDARD_LICENCE_CONDITIONS.rtf
=> fix: add correct year for road traffic act 1988

composer.lock
=> chore: bump `olcs-utils` to `5.0.0-beta.2`

module/Api/src/Domain/CommandHandler/PrintScheduler/PrintJob.php, test/module/Api/src/Domain/CommandHandler/PrintScheduler/PrintJobTest.php
The printing shell commands aren't seemingly returning 0 exit codes. This changes the code to assume that if no output then the command ran successfully.
=> fix: assume zero-exit code for print shell commands if not set

module/AcquiredRights/test/Client/Mapper/ApplicationReferenceMapperTest.php, module/AcquiredRights/test/Exception/Mapper/AcquiredRightsExceptionToValidationExceptionMapperTest.php, module/AcquiredRights/test/Service/AcquiredRightsServiceTest.php, module/Auth/test/Adapter/CognitoAdapterTest.php, test/module/Api/src/Domain/CommandHandler/Application/UpdateVariationCompletionTest.php
Some test data provider names were not updated with the migration PR. This links them back to their respective provider.
=> fix: correct test data provider method names

module/Cpms/test/Client/HttpClientTest.php, module/Cpms/test/Service/ApiServiceTest.php, test/module/Api/src/Service/Cpms/ApiServiceFactoryTest.php, test/module/Api/src/Service/Document/DocumentTest.php, test/module/Api/src/Service/DvlaSearch/DvlaSearchServiceFactoryTest.php, test/module/Api/src/Service/Ebsr/Filter/InjectIsTxcAppTest.php, test/module/Api/src/Service/Ebsr/RulesValidator/EffectiveDateTest.php, test/module/AwsSdk/src/Factories/S3ClientFactoryTest.php, test/module/AwsSdk/src/Factories/SqsClientFactoryTest.php, test/module/Queue/src/Factories/MessageBuilderFactoryTest.php, test/module/Queue/src/Factories/QueueFactoryTest.php
The unit tests part of this PR used Mockery to mock objects, however didn't include a tear down (provided by the `MockeryTestCase`). This caused flakiness in other tests.
This PR updates the parent of tests that require a Mockery tear down.
=> fix: improve stability of unit tests

test/module/Api/src/Domain/CommandHandler/CommandHandlerTestCase.php, test/module/Api/src/Domain/CommandHandler/Fee/RefundFeeTest.php, test/module/Api/src/Domain/QueryHandler/QueryHandlerTestCase.php, test/module/Api/src/Domain/Repository/RepositoryTestCase.php, test/module/Api/src/Entity/Abstracts/EntityTester.php
Removes custom `tearDown` in unit tests.
Moves assertions that happened in `tearDown` to `assertPostConditions` method (runs between the test and `tearDown`) and is the correct method for these assertions that were in the `tearDown`.
=> fix: further unit test stability improvements

test/module/Api/src/Domain/Validation/ImplementationTest.php, test/module/Api/src/Service/Publication/Context/PluginManagerTest.php, test/module/Api/src/Service/Publication/Process/PluginManagerTest.php, test/module/Api/src/Service/Submission/Sections/SectionGeneratorPluginManagerTest.php, test/module/Cli/src/Service/Queue/MessageConsumerManagerTest.php, test/src/MocksRepositoriesTrait.php
Fixes the following deprecation reported during unit tests:
```
PHP Deprecated:  Laminas\ServiceManager\AbstractPluginManager::__construct now expects a Psr\Container\ContainerInterface instance representing the parent container; please update your code in /home/runner/work/olcs-backend/olcs-backend/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php on line 99
```
=> fix: refactor Laminas deprecations out of unit tests

module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversation.php
Add the conversation data to the conversation message page to support checking isClosed.
Related issue: [VOL-4689](https://dvsa.atlassian.net/browse/VOL-4689)
=> feat: Close Conversation FE - add conversation in to result page

module/Api/config/command-map.config.php, test/module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversationTest.php
Adding the conversation object to the message list page broke the list page query handler test.
Refactor of Close class did not pick up the command map php change.
=> fix: Conversation added to message list page broke test. Refactor of Close missed in map.

module/Api/src/Domain/CommandHandler/Messaging/Conversation/Close.php
The command is able to be executed and handled despite the feature toggle messaging being inactive.
Related issue: [4842](https://dvsa.atlassian.net/browse/VOL-4842)
=> fix: Block Conversation Close with feature flag

.phpstorm.meta.php, composer.lock, module/Api/config/command-map.config.php, module/Api/config/module.config.php, module/Api/config/validation-map/messaging.config.php, module/Api/src/Domain/CommandHandler/Messaging/Conversation/Disable.php, module/Api/src/Domain/CommandHandler/Messaging/Conversation/Enable.php, test/module/Api/src/Domain/CommandHandler/Messaging/Conversation/Disable.php, test/module/Api/src/Domain/CommandHandler/Messaging/Conversation/Enable.php
Caseworkers can disable messaging functionality for a VOL user. This would be used in instances where the user was abusing the system or breaching terms of service.
Related issue: [VOL-4388](https://dvsa.atlassian.net/browse/VOL-4388)
=> feat: Messaging user level disable/enable

module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversation.php, test/module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversationTest.php
Call serialize() on the conversation object to prevent recursion.
Related issue: [VOL-4917](https://dvsa.atlassian.net/browse/VOL-4917)
=> fix: Prevent recursion on message list

module/Api/src/Domain/Repository/Queue.php, test/module/Api/src/Domain/Repository/QueueTest.php
Continuation not sought batch job had been broken by the Doctrine upgrade. This fixes that and also introduces bound params.
Related issue: [VOL-4944](https://dvsa.atlassian.net/browse/VOL-4944)
=> fix: VOL-4944 update continuation not sought to use bound params and Doctrine Result class

module/Api/src/Domain/Repository/Task.php, test/module/Api/src/Domain/Repository/TaskTest.php
fix up flag-urgent-tasks batch job - now works locally again.
Related issue: [4963](https://dvsa.atlassian.net/browse/VOL-4963)
=> fix: flag-urgent-tasks batch job getCalls and deprecated doctrine method

composer.lock, module/Api/src/Domain/CommandHandler/Task/CreateTask.php
Last TM letter batch job erroring due to CreateTask::getMessaging() method
Related issue: [VOL-4975](https://dvsa.atlassian.net/browse/VOL-4975)
=> fix: Add missing messaging flag for backend.

module/Api/src/Domain/Repository/Bus.php, module/Cli/src/Domain/CommandHandler/Bus/Expire.php, test/module/Api/src/Domain/Repository/BusTest.php, test/module/Cli/src/Domain/CommandHandler/Bus/ExpireTest.php
Bus Reg expiry batch job didn't previously display how many registrations had been expired. This adds that in, to allow a better idea at a glance of whether the job is behaving correctly.
Related issue: [VOL-4994](https://dvsa.atlassian.net/browse/VOL-4994)
=> feat: VOL-4994 bus reg expiry batch job now returns number of expired records

module/Api/src/Domain/CommandHandler/Messaging/Message/Create.php
When a new conversation is created, the correlation ID is null due to no uploads.
=> fix: Check for correlation ID for uploads being null

module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByLicence.php, module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByOrganisation.php, module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversation.php, module/Api/src/Domain/Repository/Message.php
Use both conversation and message on join to avoid lack of index use (MySQL not picking conversation index).
=> fix: Slow join on documents to messages.

module/Api/src/Domain/CommandHandler/InspectionRequest/SendInspectionRequest.php, module/Api/src/Entity/System/SystemParameter.php, test/module/Api/src/Domain/CommandHandler/InspectionRequest/SendInspectionRequestTest.php
Change SendInspectionRequest command handler to use System Parameter value for GB and NI EMS emails, replacing the use of 14 different emails from the DB.
Related issue: [VOL-5011](https://dvsa.atlassian.net/browse/VOL-5011)
=> feat: Update SendInspectionRequest to use sysParam for to: email address

module/Api/src/Domain/Command/Email/CreateCorrespondenceRecord.php, module/Api/src/Domain/CommandHandler/Messaging/Conversation/Close.php, module/Email/view/email/cy_GB/html/licensing-information-conversation.phtml, module/Email/view/email/cy_GB/plain/licensing-information-conversation.phtml, module/Email/view/email/en_GB/html/licensing-information-conversation.phtml, module/Email/view/email/en_GB/plain/licensing-information-conversation.phtml
Custom email content for closed and archived conversation.
Related issue: [VOL-5081](https://dvsa.atlassian.net/browse/VOL-5081)
=> feat: Custom email for closed and archived conversation

module/Email/view/email/cy_GB/html/licensing-information-conversation.phtml, module/Email/view/email/cy_GB/plain/licensing-information-conversation.phtml, module/Email/view/email/en_GB/html/licensing-information-conversation.phtml, module/Email/view/email/en_GB/plain/licensing-information-conversation.phtml
Change the word continuation to conversation.
Related issue: [VOL-5081](https://dvsa.atlassian.net/browse/VOL-5081)
=> fix: Change continuation to conversation in the email body

module/Api/src/Domain/CommandHandler/Messaging/Message/Create.php
Add message attachments to the document list in internal.
Related issue: [VOL-5118](https://dvsa.atlassian.net/browse/VOL-5118)
=> feat: Show message attachments in the internal document list

composer.lock, module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversation.php, module/Api/src/Domain/Repository/AbstractReadonlyRepository.php, module/Api/src/Domain/Repository/Message.php, test/module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversationTest.php
Add a footer to internal to show the first operator to read the message.
Related issue: [VOL-5082](https://dvsa.atlassian.net/browse/VOL-5082)
=> feat: Message footer showing operator first read

.gitignore, config/autoload/global.php, data/cache/DoctrineORMModule/.gitignore
Updates the cache directory of Doctrine from `/tmp` to `data/cache/DoctrineORMModule`. This consolidates the directories that are needed by the application to simplify permissions.
Related issue: https://dvsa.atlassian.net/browse/VOL-4679
=> feat: change Doctrine cache directory

module/Api/src/Domain/QueryHandler/Messaging/Conversations/AbstractConversationQueryHandler.php, test/module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByLicenceTest.php, test/module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByOrganisationTest.php
Include operator admin role in messaging filtering.
Related issue: [VOL-5114](https://dvsa.atlassian.net/browse/VOL-5114)
=> fix: Add ROLE_OPERATOR_ADMIN to messaging filtering roles

module/Api/config/validation-map/messaging.config.php, module/Api/src/Domain/Validation/Handlers/Messaging/CanAccessCorrelatedDocuments.php, module/Api/src/Domain/Validation/ValidationHelperTrait.php, module/Api/src/Domain/Validation/Validators/CanAccessDocument.php, module/Api/src/Entity/Doc/Document.php, test/module/Api/src/Domain/Validation/ValidationHelperTestCaseTrait.php, test/module/Api/src/Domain/Validation/Validators/CanAccessCorrelatedDocumentsTest.php, test/module/Api/src/Domain/Validation/Validators/CanAccessDocumentTest.php
When creating a conversation, it was failing as permissions were trying to check document ID’s that didn’t exist. 
Related issue: [VOL-5175](https://dvsa.atlassian.net/browse/VOL-5175)
=> fix: Validator for messaging attachments based on correlation ID

module/Api/config/command-map.config.php, module/Api/config/validation-map/messaging.config.php, module/Api/src/Domain/Command/Messaging/Conversation/StoreEnhancedSnapshot.php, module/Api/src/Domain/CommandHandler/Messaging/Conversation/Close.php, module/Api/src/Domain/CommandHandler/Messaging/Conversation/StoreEnhancedSnapshot.php, module/Snapshot/config/module.config.php, module/Snapshot/src/Service/Snapshots/Messaging/EnhancedGenerator.php, module/Snapshot/src/Service/Snapshots/Messaging/EnhancedGeneratorFactory.php, module/Snapshot/view/layout/conversation.phtml, module/Snapshot/view/partials/read-only/printable-message.phtml, test/module/Api/src/Domain/CommandHandler/Messaging/Conversation/Close.php, test/module/Api/src/Domain/CommandHandler/Messaging/Conversation/StoreEnhancedSnapshotTest.php
Create an enhance snapshot on conversation close (includes readers).
Related issue: [VOL-5083](https://dvsa.atlassian.net/browse/VOL-5083)
=> feat: Enhanced conversation snapshot

module/Api/src/Entity/Licence/Licence.php, test/module/Api/src/Entity/Application/ApplicationEntityTest.php, test/module/Api/src/Entity/Licence/LicenceEntityTest.php
Don't count vehicles on cancelled applications against validation check
Related issue: [VOL-3941](https://dvsa.atlassian.net/browse/VOL-3941)
=> fix: Don't count vehicles on cancelled applications against validation check

module/Api/src/Domain/CommandHandler/CompaniesHouse/Compare.php, test/module/Api/src/Domain/CommandHandler/CompaniesHouse/CompareTest.php
Occasional problems are occurring when processing insolvent companies. This logging will allow us to see what's going on and correct the problem.
Related issue: [VOL-5111](https://dvsa.atlassian.net/browse/VOL-5111)
=> feat: VOL-5111 add logging of company insolvency check

module/Api/src/Domain/CommandHandler/Auth/Login.php, module/Api/src/Domain/Repository/User.php
Directly update user last login via DQL to avoid optimistic lock.
Related issue: [VOL-5251](https://dvsa.atlassian.net/browse/VOL-5251)
=> fix: Update use last login using DQL to prevent optimistic lock

module/Api/src/Domain/CommandHandler/Traits/DeleteContactDetailsAndAddressTrait.php, test/module/Api/src/Domain/CommandHandler/Licence/SaveAddressesTest.php, test/module/Api/src/Domain/CommandHandler/Traits/DeleteContactDetailsAndAddressTraitTest.php, test/module/Api/src/Domain/CommandHandler/Workshop/DeleteWorkshopTest.php
Refresh address before delete as it may have changed further up the stack.
Related issue: [VOL-3410](https://dvsa.atlassian.net/browse/VOL-3410)
=> fix: remove transport manager address optimistic lock

module/Api/src/Domain/CommandHandler/Surrender/Approve.php
There is a bug in VOL which is currently preventing caseworkers surrendering PSV special restricted licences via the internal caseworker system. This is present in both production and PP upon test. 
Related issue: [VOL-3456](https://dvsa.atlassian.net/browse/VOL-3456)
=> fix: Allow special restricted licence surrender

module/Api/src/Entity/Licence/Licence.php, test/module/Api/src/Entity/Application/ApplicationEntityTest.php, test/module/Api/src/Entity/Licence/LicenceEntityTest.php
fix: Allow a previously used vehicle to be re-used
Related issue: [VOL-3941](https://dvsa.atlassian.net/browse/VOL-3941)
=> fix: Allow a previously used vehicle to be re-used

module/Api/src/Domain/CommandHandler/Application/ResetApplication.php, module/Api/src/Domain/CommandHandler/Traits/ApplicationResetTrait.php, module/Api/src/Domain/CommandHandler/Variation/ResetVariation.php, test/module/Api/src/Domain/CommandHandler/Application/ResetApplicationTest.php, test/module/Api/src/Domain/CommandHandler/Variation/ResetVariationTest.php
Remove association between application and operator on application/variation reset
Related issue: https://dvsa.atlassian.net/browse/VOL-3736
=> fix: Remove association between application and operator on application/variation reset

module/Api/src/Domain/Validation/Validators/CanAccessDocument.php, test/module/Api/src/Domain/Validation/Validators/CanAccessDocumentTest.php
Recent tightening of permission in CanAccessDocument validator has prevented the "Print Licence" link on the licence view page. This adds a new check to allow download of matching documents.
Related issue: [VOL-5381](https://dvsa.atlassian.net/browse/VOL-5381)
=> fix: Add extra check to CanAccessDocument validator to fix SS bug VOL-5381

module/Api/src/Domain/QueryHandler/Application/Summary.php, module/Api/src/Domain/Repository/Cases.php, test/module/Api/src/Domain/QueryHandler/Application/SummaryTest.php, test/module/Api/src/Domain/Repository/CasesTest.php
The original issue was the `fetchOpenCasesForApplication` returned a Cases Entity object. This isn't countable and throws an error in PHP 8.0+.
Noticed there's quite confusing logic and refactored:
- Strongly typed the `fetchOpenCasesForApplication` to always return an array. 
- Removed the throwing of an exception if there are no open cases, this isn't required and is hiding unit test failures. 
- Updated the unit tests to add more accurate coverage.
Related issue: https://dvsa.atlassian.net/browse/VOL-5469
=> fix: fix application open cases method

module/Olcs/Db/src/Service/Search/QueryTemplate.php, test/module/Olcs/Db/src/Service/Search/QueryTemplateTest.php
The `AbstractIndex->getFilter` isn't a method. This interface did have `getFilters` though. This returned an array of filters. This PR refactors the code to use the correct methods and handle the return types properly.
Related issue: https://dvsa.atlassian.net/browse/VOL-5446
=> fix: refactor to use correct `AbstractIndex` contract

module/Api/src/Domain/QueryHandler/Document/AbstractDownload.php, module/Api/src/Domain/QueryHandler/Document/Download.php, module/Api/src/Domain/QueryHandler/Document/DownloadGuide.php, module/DocumentShare/src/Service/DocManClient.php, module/DocumentShare/src/Service/WebDavClient.php, test/module/Api/src/Domain/QueryHandler/Document/AbstractDownloadStub.php, test/module/Api/src/Domain/QueryHandler/Document/AbstractDownloadTest.php, test/module/Api/src/Domain/QueryHandler/Document/DownloadGuideTest.php, test/module/Api/src/Domain/QueryHandler/Document/DownloadTest.php, test/module/Api/src/Domain/QueryHandler/QueryHandlerTestCase.php, test/module/Api/src/Service/File/ContentStoreFileUploaderTest.php
Downloaded files now use the document description as the filename
Behaviour is changed for internal users only.
Also fixed inconsistency between how webdav and docman clients return when a file doesn't exist.
Related issue: [VOL-5276](https://dvsa.atlassian.net/browse/VOL-5276)
=> feat: downloaded files now use the document description where available

.github/workflows/ci.yaml, .github/workflows/static-analysis.yaml
This fixes the CI workflow where Psalm now fails because PHP does not have Redis with IGBinary extension enabled (thus constant did not exist).
As a temporary measure, we copy-pasta the Static Analysis workflow from [dvsa/.github/workflows/php-static.yml](https://github.com/dvsa/.github/blob/main/.github/workflows/php-static.yml) and modify Setup PHP to compile Redis from source with support for IGBinary.
Related issue: https://dvsa.atlassian.net/browse/VOL-5559
=> fix: Psalm & Redis IGBinary issue

module/Api/src/Domain/QueryHandler/Irfo/IrfoGvPermitTypeList.php, module/Api/src/Domain/Repository/IrfoGvPermitType.php, module/Api/src/Entity/Irfo/AbstractIrfoGvPermitType.php, test/module/Api/src/Domain/QueryHandler/Irfo/IrfoGvPermitTypeListTest.php, test/module/Api/src/Domain/Repository/IrfoGvPermitTypeTest.php
Filter out unused IRFO Permit types from drop down
Related issue: [VOL-5009](https://dvsa.atlassian.net/browse/VOL-5009)
=> feat: Add display until support to IRFO GV Permit type

composer.json, composer.lock, module/Api/config/command-map.config.php, module/Api/config/query-map.config.php, module/Api/config/validation-map/local-authority.config.php, module/Api/src/Domain/CommandHandler/LocalAuthority/Update.php, module/Api/src/Domain/QueryHandler/LocalAuthority/ById.php, module/Api/src/Entity/Bus/LocalAuthority.php, test/module/Api/src/Domain/CommandHandler/LocalAuthority/UpdateTest.php, test/module/Api/src/Domain/QueryHandler/LocalAuthority/ByIdTest.php, test/module/Api/src/Entity/LocalAuthority/LocalAuthorityEntityTest.php
Local Authority Admin Edit Functionality
Related issue: [VOL-5532](https://dvsa.atlassian.net/browse/VOL-5532)
=> feat: Add backend api support for Local Authority UI

config/autoload/config.global.php
As title.
Context is that we're logging a lot of information at the moment and missing vital parts.
=> feat: change logging level to `WARN`

module/Api/config/command-map.config.php, module/Api/config/validation-map/private-hire-licence.config.php, module/Api/src/Domain/CommandHandler/Application/SetDefaultTrafficAreaAndEnforcementAreaFactory.php, module/Api/src/Domain/CommandHandler/PrivateHireLicence/CreateFactory.php, module/Api/src/Domain/CommandHandler/PrivateHireLicence/UpdateFactory.php
Fixes the factories for the command handlers changed introduced through https://github.com/dvsa/olcs-backend/pull/197 and ensured the changed command handlers use the factories.
=> fix: Fixes factories for command handlers and types

module/Queue/src/Service/QueueServiceTrait.php, test/module/Cli/src/Domain/CommandHandler/MessageQueue/Consumer/TransXChange/TransXChangeConsumerTest.php
Two separate changes were made, to prevent the queue service being overwritten, which cancelled each other out :)
Have reverted one of them, which also handily reverts the code to a previous state and removes risk of the other service using this, companies house, from being impacted.
Related issue: [VOL-3953](https://dvsa.atlassian.net/browse/VOL-3953)
=> fix: VOL-3953 prevent bug with queue service from being overwritten

module/Email/view/email/en_GB/html/email-inbox-reminder-continuation.phtml, module/Email/view/email/en_GB/plain/email-inbox-reminder-continuation.phtml
Update continuation reminder emails to use content from translation keys.
Related issue: [VOL-5695](https://dvsa.atlassian.net/browse/VOL-5695)
=> feat: update continuation reminder email template

config/autoload/config.global.php
The app used to re-use the TransXChange parameters for the token URL. However, TransXChange isn't using the production AzureAD tenant for INT/PP.
=> fix: use specific address service token URL
