- module/DocumentShare/src/Service/ClientFactory.php
- test/module/DocumentShare/src/Service/ClientFactoryTest.php
Enforces WebDav for all users. This is controlled by the `enforce_webdav` feature toggle.
Related issue: https://dvsa.atlassian.net/browse/VOL-4638
> fix: add feature toggle functionality to force WebDav

- module/Api/config/command-map.config.php
- module/Api/config/validation-map/messaging.config.php
- module/Api/src/Domain/CommandHandler/Messaging/Close.php
- module/Api/src/Domain/CommandHandler/Messaging/Conversation/Close.php
Add the ability to mark a conversation as closed.
Related issue: [VOL-4573](https://dvsa.atlassian.net/browse/VOL-4573)
> feat: Close Handler for Conversations

- composer.json
- composer.lock
Switch composer packages for OLCS to dev-project/messaging
> feat: OLCS composer packages to dev-project/messaging

- composer.lock
- module/Api/config/module.config.php
- module/Api/config/query-map.config.php
- module/Api/config/validation-map/messaging.config.php
- module/Api/src/Domain/QueryHandler/Category/GetList.php
- module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByApplicationToOrganisation.php
- module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByLicenceToOrganisation.php
- module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByOrganisation.php
- module/Api/src/Domain/Repository/Application.php
- module/Api/src/Entity/Application/Application.php
- test/module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByApplicationToOrganisationTest.php
- test/module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByLicenceToOrganisationTest.php
- test/module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByOrganisationTest.php
- test/module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByLicenceTest.php
- test/module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversationTest.php
This query is to provide Licence & Application ids (by org id) for use in create Conversation interface
Related issue: [VOL-4681](https://dvsa.atlassian.net/browse/VOL-4681)
Related issue: [VOL-4737](https://dvsa.atlassian.net/browse/VOL-4737)
> feat: Query to list Licence & Application numbers

- module/Api/src/Domain/Repository/Queue.php
- test/module/Api/src/Domain/Repository/QueueTest.php
Removes obsolete Companies House method from Queue repo 
Related issue: [VOL-4953](https://dvsa.atlassian.net/browse/VOL-4953)
> refactor: VOL-4953 remove obsolete companies house method

- composer.lock
- module/Api/src/Domain/Command/Task/CreateTask.php
- module/Api/src/Domain/CommandHandler/Messaging/Conversation/Create.php
- module/Api/src/Domain/CommandHandler/Task/CreateTask.php
- module/Api/src/Domain/QueryHandler/Task/TaskList.php
- module/Api/src/Domain/Repository/TaskSearchView.php
- module/Api/src/Entity/Task/AbstractTask.php
- module/Api/src/Entity/View/TaskSearchView.php
- test/module/Api/src/Domain/Command/Task/CreateTaskTest.php
- test/module/Api/src/Domain/Repository/TaskSearchViewTest.php
- test/module/Api/src/Entity/View/TaskSearchViewTest.php
Messaging creates a messaging flag task. Tasks are filterable by the messaging flag.
Related issue: [VOL-4381](https://dvsa.atlassian.net/browse/VOL-4381)
> feat: Task messaging filter (home page)

- module/Api/src/Domain/CommandHandler/DataRetention/Populate.php
- module/Api/src/Domain/CommandHandler/DataRetention/Precheck.php
- module/Api/src/Domain/QueryHandler/DataRetention/Postcheck.php
- module/Api/src/Domain/QueryHandler/Diagnostics/CheckFkIntegrity.php
- module/Api/src/Domain/QueryHandler/Diagnostics/GenerateCheckFkIntegritySql.php
- test/module/Api/src/Domain/CommandHandler/DataRetention/PopulateTest.php
- test/module/Api/src/Domain/CommandHandler/DataRetention/PrecheckTest.php
- test/module/Api/src/Domain/QueryHandler/DataRetention/PostcheckTest.php
- test/module/Api/src/Domain/QueryHandler/Diagnostics/CheckFkIntegrityTest.php
- test/module/Api/src/Domain/QueryHandler/Diagnostics/GenerateCheckFkIntegritySqlTest.php
Fix container get for entity manager
Related issue: [VOL-4967](https://dvsa.atlassian.net/browse/VOL-4967)
> fix: Correct get call for DoctrineEntityManager

- .phpstorm.meta.php
- module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByApplicationToLicence.php
- module/Api/src/Domain/Repository/Application.php
- test/module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByApplicationToLicenceTest.php
Adds messaging to the application/ routes.
Related issue: [TBC](TBC)
> feat: Add application to response for linking

- module/Api/config/command-map.config.php
- module/Api/config/validation-map/messaging.config.php
- module/Api/src/Domain/Command/Messaging/Conversation/StoreSnapshot.php
- module/Api/src/Domain/CommandHandler/Messaging/Conversation/Close.php
- module/Api/src/Domain/CommandHandler/Messaging/Conversation/StoreSnapshot.php
- module/Api/src/Entity/Messaging/MessagingConversation.php
- module/Api/src/Entity/System/SubCategory.php
- module/Snapshot/config/module.config.php
- module/Snapshot/src/Service/Snapshots/Messaging/Generator.php
- module/Snapshot/src/Service/Snapshots/Messaging/GeneratorFactory.php
- module/Snapshot/view/layout/conversation.phtml
- module/Snapshot/view/partials/read-only/printable-message.phtml
- test/module/Api/src/Domain/CommandHandler/Messaging/Conversation/StoreSnapshotTest.php
Create a HTML snapshot, store in doc store + DB.
Related issue: [VOL-4673](https://dvsa.atlassian.net/browse/VOL-4673)
> feat: Conversation snapshot (and document) on close

- module/Api/src/Domain/CommandHandler/Messaging/Conversation/StoreSnapshot.php
- module/Api/src/Entity/System/SubCategory.php
- test/module/Api/src/Domain/CommandHandler/Messaging/Conversation/StoreSnapshotTest.php
Use Other Documents sub category for Message Archiving
Related issue: [VOL-4673](https://dvsa.atlassian.net/browse/VOL-4673)
> feat: Use Other Documents for Message Archiving

- .snyk
Ignore the various license issues that are getting raised by Snyk.
Related issue: https://dvsa.atlassian.net/browse/VOL-4785
> chore: add `.synk` to exclude license issues

- composer.lock
Bump `olcs-utils` and `olcs-xmltools`
> chore: bump `olcs-utils` & `olcs-xmltools`

- module/Api/src/Domain/CommandHandler/Messaging/Message/Create.php
- module/Api/src/Domain/Validation/Handlers/Document/CanCreateDocument.php
- test/module/Api/src/Domain/Validation/Handlers/Document/CanCreateDocumentTest.php
Allow uploads when starting a new conversation.
Related issue: [VOL-5120](https://dvsa.atlassian.net/browse/VOL-5120)
> feat: Handle uploads on new conversation from SS.

- module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByOrganisation.php
- test/module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByOrganisationTest.php
Filter application options when Operator creates a new conversation
Related issue: [VOL-5092](https://dvsa.atlassian.net/browse/VOL-5092)
> feat: Filter application options when creating new conversation

- config/autoload/config-parameters.global.php
- config/autoload/config.global.php
Tweaks the secret name template for config. This is messy and will be cleaned in the migration to ECS.
> fix: fix secret name template

- module/Api/src/Domain/QueryHandler/Messaging/Message/ByConversation.php
- module/Olcs/Db/src/Controller/SearchController.php
- module/Olcs/Db/src/Service/Search/QueryTemplate.php
- module/Olcs/Db/src/Service/Search/Search.php
- test/module/Olcs/Db/src/Service/Search/QueryTemplateTest.php
Transport manager deleted/merged search filters
Related issue: [VOL-3539](https://dvsa.atlassian.net/browse/VOL-3539)
> feat: Transport manager deleted/merged search filters

- composer.json
- composer.lock
- module/Auth/src/Service/PasswordService.php
- module/Auth/test/Service/PasswordServiceTest.php
Removed unused dependency
Related issue: [VOL-5168](https://dvsa.atlassian.net/browse/VOL-5168)
> chore: Remove fzaninotto/faker dependency

- composer.lock
- test/module/Api/src/Domain/CommandHandler/Trailer/UpdateTrailerTest.php
- test/module/Api/src/Domain/QueryHandler/Bus/BusRegBrowseContextListTest.php
- test/module/Api/src/Domain/Repository/DataRetentionTest.php
Bump olcs-transfer dep to 6.8.0
> chore: Bump olcs-transfer to 6.8.0

- module/Api/src/Entity/User/User.php
Reverting a property promotion tweak made by rector which breaks the app.
> fix: User entity property promotion breaks the app

- module/Api/src/Domain/QueryHandler/TmResponsibilities/TmResponsibilitiesList.php
- test/module/Api/src/Domain/QueryHandler/TmResponsibilities/TmResponsibilitiesListTest.php
TM responsibilities should show surrender under consideration.
Related issue: [VOL-826](https://dvsa.atlassian.net/browse/VOL-826)
> fix: TM responsibilities should show surrender under consideration

- composer.json
- composer.lock
- module/Api/src/Domain/QueryHandler/Organisation/OutstandingFees.php
- module/Api/src/Domain/Repository/Fee.php
- test/module/Api/src/Domain/QueryHandler/Organisation/OutstandingFeesTest.php
Only show fees for submitted applications.
Related issue: [VOL-233](https://dvsa.atlassian.net/browse/VOL-233)
> fix: Only show valid fees for licences

- module/Api/src/Domain/CommandHandler/CompaniesHouse/Compare.php
- module/Cli/src/Domain/CommandHandler/MessageQueue/Consumer/CompaniesHouse/CompanyProfile.php
Companies house insolvency check wasn't being properly cleared at the end of each request
Related issue: [VOL-5111](https://dvsa.atlassian.net/browse/VOL-5111)
> fix: companies house code now checks insolvency flag properly

- module/Api/config/validation-map/irfo.config.php
Internal users now require edit permissions for irfo gv permit actions
Related issue: [VOL-5226](https://dvsa.atlassian.net/browse/VOL-5226)
> fix: VOL-5226 tighten permissions for irfo gv permit actions

- module/Api/src/Domain/Validation/Validators/CanAccessDocument.php
Extra descriptions to match added.
> fix: Ss cant print licence bugfix vol 5381 extra descriptions

- composer.json
- composer.lock
- module/Api/src/Domain/QueryHandler/Organisation/OutstandingFees.php
- module/Api/src/Domain/Repository/Fee.php
- test/module/Api/src/Domain/QueryHandler/Organisation/OutstandingFeesTest.php
> chore: revert "fix: Only show valid fees for licences"

- composer.json
- composer.lock
- module/Api/src/Domain/Repository/Conversation.php
- test/module/Api/src/Domain/Repository/ConversationTest.php
Upgrade to Doctrine 2.19.5
Related issue: [VOL-4507](https://dvsa.atlassian.net/browse/VOL-4507)
> feat!: VOL-4507 Upgrade to Doctrine 2.19.5

- module/Api/config/command-map.config.php
- module/Api/config/module.config.php
- module/Api/config/validation-map/bus.config.php
- module/Api/src/Domain/Command/Email/SendBSRNotificationToLTAs.php
- module/Api/src/Domain/CommandHandler/Bus/GrantBusReg.php
- module/Api/src/Domain/CommandHandler/Bus/PrintLetter.php
- module/Api/src/Domain/CommandHandler/Email/AbstractEmailHandler.php
- module/Api/src/Domain/CommandHandler/Email/SendBSRNotificationToLTAs.php
- test/module/Api/src/Domain/CommandHandler/Bus/GrantBusRegTest.php
- test/module/Api/src/Domain/CommandHandler/Bus/PrintLetterTest.php
Stop force-printing manual BSR letters, send via email attachment to relevant LTAs instead.
Related issue: [VOL-5423](https://dvsa.atlassian.net/browse/VOL-5423)
> feat: BSR LTA email notifications 

- composer.json
- config/application.config.php
- module/Db/src/Module.php
Fix for module broken after namespace normalisation work
> fix: fix for Db module not being included correctly causing some issues.

- module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByOrganisation.php
- test/module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByOrganisationTest.php
Filter Licences shown in Create Message page drop down filter by suitable statuses.
Related issue: [VOL-5572](https://dvsa.atlassian.net/browse/VOL-5572)
> feat: Filter licences by status for Create Message App/Lic dropdown.

- config/autoload/config.global.php
- module/DvsaAddressService/src/Client/DvsaAddressServiceClientFactory.php
Added Proxy Support for DVSA Address Service
Related issue: https://dvsa.atlassian.net/browse/VOL-5544
> fix: added proxy support for DVSA Address Service

- module/Api/src/Entity/System/FeatureToggle.php
Add feature toggle for transport consultant role
Related issue: [VOL-5249](https://dvsa.atlassian.net/browse/VOL-5249)
> feat: VOL-5249 add feature toggle for transport consultant role

- module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByApplicationToLicence.php
- test/module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByApplicationToLicenceTest.php
Remove array walk. It was not iterating. No functional difference.
> fix: remove array walk

- module/Cli/src/Domain/CommandHandler/MessageQueue/Consumer/TransXChange/TransXChangeConsumer.php
- test/module/Cli/src/Domain/CommandHandler/MessageQueue/Consumer/TransXChange/TransXChangeConsumerTest.php
Points the proxy setting to the correct key in config. Fixes the timeouts.
> fix: fix config key for TransXChange proxy
